name: tekartik_sc
version: 0.4.0
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/sc.dart
dependencies:
  process_run: '>=0.5.4'
  # args: '>=1.0.1' grinder incompatible
  args: '>=0.13.7'
  path: '>=1.4.2'
  pub_semver: '>=0.5.4'
  logging: '>=0.11.3'
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
  tekartik_io_utils:
    git: git://github.com/tekartik/io_utils.dart

dev_dependencies:
  test: any
  dev_test: '>=0.9.3'
  tekartik_pub:
    git: git://github.com/tekartik/pub.dart
dependency_overrides:
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
#    path: ../process_run.dart
executables:
  scpull:
  scstatus:
  screvert:
  scpp:
  scclone: