name: tekartik_sc
version: 0.10.2

homepage: https://github.com/tekartik/sc.dart
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  process_run: '>=0.10.9'
  # args: '>=1.0.1' grinder incompatible
  args: '>=0.13.7'
  path: '>=1.4.2'
  pub_semver: '>=0.5.4'
  logging: '>=0.11.3'
  pool:
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
      ref: dart2_3
    version: '>=0.5.1'
dev_dependencies:
  test: any
  dev_test: '>=0.13.2-dev.2'
  build_runner: '>=0.9.1'
  build_test: '>=0.10.2'
  chrome_travis:
    git:
      url: https://github.com/tekartik/chrome_travis.dart
      ref: dart2_3
    version: '>=0.1.4'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.5.1'

dependency_overrides:
#  process_run:
#    git: https://github.com/tekartik/process_run.dart
#    path: ../process_run.dart
